os: windows

language: shell

before_install: choco install r --version=3.6.2

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

powershell:
  - Rscript.exe -e "renv::restore()"
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh 
