os: windows

language: shell

before_install: choco install r --version=3.6.2

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

script:
  - Powershell C:\Program` Files\R\R-3.6.2\bin\Rscript.exe -e "renv::restore()" 
