os: windows
language: bash

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey

install:
 - choco install -y r --version 3.6.2
 - choco install -y rtools --version 3.5.0.4
 - choco install -y miktex --version=2.9.7079
 - "export PATH=/c/Program\\ Files/MiKTeX\\ 2.9/miktex/bin/x64:$PATH"
 - choco install -y pandoc
 - "export PATH=/c/Program\\ Files/R/R-3.6.2/bin/x64:/c/Rtools/bin:/c/RTools/mingw_64/bin:$PATH"
 - mkdir -p ${HOME}/Documents/R/win-library/3.6
 - export R_LIBS_USER=${HOME}/Documents/R/win-library/3.6
 - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > .Rprofile
 - Rscript -e 'install.packages("devtools")'
 - Rscript -e 'install.packages("renv")'
 - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
script:
 - Rscript -e 'renv::restore()'
