# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2' # The R version to download (if necessary) and use.
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
    - name: Install dependencies
      run: |
          renv::activate() 
          renv::upgrade()
          renv::restore()
          source("run.R")
      shell: Rscript {0}
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
          name: my-artifact
          path: Outputs/report.html
